# Generated by Django 5.1.2 on 2024-12-10 02:37

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('account_type', models.CharField(choices=[('savings', 'Savings'), ('credit', 'Credit'), ('chequing', 'Chequing')], default='chequing', max_length=50)),
                ('currency', models.CharField(choices=[('cad', 'CAD'), ('usd', 'USD'), ('eur', 'EUR')], default='cad', max_length=3)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.bank')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('priority', models.IntegerField()),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['priority'],
            },
        ),
        migrations.CreateModel(
            name='CategoryRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_text', models.CharField(max_length=50)),
                ('match_type', models.CharField(choices=[('equals', 'Equals'), ('contains', 'Contains'), ('regex', 'Regex'), ('starts_with', 'Starts with'), ('ends_with', 'Ends with')], default='contains', max_length=50)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rule_set', to='main_app.category')),
            ],
        ),
        migrations.CreateModel(
            name='ParseRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('date_fmt_str', models.CharField(max_length=30)),
                ('csv_delim', models.CharField(blank=True, default=',', max_length=1)),
                ('start_line', models.IntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('date_col', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('desc_col', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('sub_desc_col', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('amount_col', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('txn_type_col', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.account')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('description', models.CharField(max_length=300)),
                ('category_override', models.BooleanField()),
                ('amount', models.FloatField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.account')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main_app.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['date', 'description'],
            },
        ),
        migrations.AddConstraint(
            model_name='bank',
            constraint=models.UniqueConstraint(fields=('name', 'user'), name='unique_bank_name'),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(fields=('name', 'user'), name='unique_category_rule_name'),
        ),
        migrations.AddConstraint(
            model_name='parserule',
            constraint=models.UniqueConstraint(fields=('name', 'user'), name='unique_parse_rule_name'),
        ),
    ]
