# Generated by Django 5.1.2 on 2024-12-10 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parserule',
            name='negate_amount',
            field=models.BooleanField(default=False),
        ),
    ]
